
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster auth testing"
  tasks:
    - name: "Cluster auth"
      cluster_auth:
        nodes: "x0rapp00leb7 x0rapp01leb7"
        username: hacluster
        password: "TestPass123!"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
      register: resultobj
    
    - name: "Cluster auth"
      cluster_auth:
        nodes: "x7rapp00l1ed x7rapp01l1ed"
        username: hacluster
        password: "TestPass123!"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
      register: resultobj
      
    - name: "Cluster auth: Output"
      debug:
        msg: '{{ resultobj }}'