
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster auth testing"
  tasks:
    - name: Cluster auth
      cluster_auth:
        os: "RedHat"
        version: "8"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        username: hacluster
        password: "TestPass123!"
      register: resultobj
      
    - name: Dump the result object
      debug:
        msg: '{{ resultobj }}'