
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster init testing"
  tasks:
    - name: "Cluster init"
      cluster_init:
        os: "RedHat"
        version: "7"
        state: present
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      