
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster init testing"
  tasks:
    - name: "Ensure cluster does not exist"
      cluster_init:
        state: absent
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      register: resultobj1
    - name: "Create cluster"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      register: resultobj2
    - name: "Remove other node"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7"
        tier: "hana"
        token: "30000"
      register: resultobj3
    - name: "Add node back"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      register: resultobj4
    - name: "Ensure idempotence"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      register: resultobj5
    - name: "Delete nonexistent cluster"
      cluster_init:
        state: absent
        sid: "idontexist"
        nodes: "x0rapp00leb7 x0rapp01leb7"
        tier: "hana"
        token: "30000"
      register: resultobj6
      
    - name: Dump the result object
      debug:
        msg: '{{ resultobj1 resultobj2 resultobj3 resultobj4 resultobj5 resultobj6 }}'
      