
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster init testing"
  tasks:
    - name: "Set the nodes list per OS"
      ansible.builtin.set_fact:
        nodelist: "x0rapp00leb7 x0rapp01leb7"
      when: ansible_os_family == "RedHat"and ansible_distribution_major_version == "8"
    
    - name: "Set the nodes list per OS"
      ansible.builtin.set_fact:
        nodelist: "x7rapp00l1ed x7rapp01l1ed"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    
    - name: "Set the nodes list per OS"
      ansible.builtin.set_fact:
        nodelist: "x00app00l650 x00app01l650"
      when: ansible_os_family == "Suse"

    - name: "Ensure cluster does not exist"
      cluster_init:
        state: absent
        sid: "wills-sid-123"
        tier: hana
      register: resultobj
    - name: "Ensure cluster does not exist: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Create cluster"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "{{ nodelist }}"
        tier: "hana"
        token: "30000"
      register: resultobj
    - name: "Create cluster: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Set node to remove per OS"
      ansible.builtin.set_fact:
        keepme: "x0rapp00leb7"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: "Set node to remove per OS"
      ansible.builtin.set_fact:
        keepme: "x7rapp00l1ed"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: "Set node to remove per OS"
      ansible.builtin.set_fact:
        keepme: "x00app00l650"
      when: ansible_os_family == "Suse"

    - name: "Remove other node"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "{{ keepme }}"
        tier: "hana"
        token: "30000"
      register: resultobj
    - name: "Remove other node: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Add node back"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "{{ nodelist }}"
        tier: "hana"
        token: "30000"
      register: resultobj
    - name: "Add node back: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Ensure idempotence"
      cluster_init:
        state: present
        sid: "wills-sid-123"
        nodes: "{{ nodelist }}"
        tier: "hana"
        token: "30000"
      register: resultobj
    - name: "Ensure idempotence: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Delete nonexistent cluster"
      cluster_init:
        state: absent
        sid: "idontexist"
      register: resultobj
    - name: "Delete nonexistent cluster: Output"
      debug:
        msg: '{{ resultobj }}'
      