
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster property testing"
  tasks:
    - name: "Ensure cluster properties are unset"
      cluster_property:
        state: absent
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: true }
        - { name: 'concurrent-fencing', value: true }
        - { name: 'stonith-timeout', value: '900' }
        - { name: 'stonith-action', value: 'reboot' }
      register: resultobj1
    - name: "unset already unset properties"
      cluster_property:
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: false }
        - { name: 'concurrent-fencing', value: false }
        - { name: 'stonith-timeout', value: '901' }
        - { name: 'stonith-action', value: 'poweroff' }
      register: resultobj2
    - name: "Ensure cluster properties are set"
      cluster_property:
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: true }
        - { name: 'concurrent-fencing', value: true }
        - { name: 'stonith-timeout', value: '900' }
        - { name: 'stonith-action', value: 'reboot' }
      register: resultobj3
    - name: "Ensure idempotence"
      cluster_property:
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: true }
        - { name: 'concurrent-fencing', value: true }
        - { name: 'stonith-timeout', value: '900' }
        - { name: 'stonith-action', value: 'reboot' }
      register: resultobj4
    - name: "Modify cluster properties"
      cluster_property:
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: false }
        - { name: 'concurrent-fencing', value: false }
        - { name: 'stonith-timeout', value: '901' }
        - { name: 'stonith-action', value: 'poweroff' }
      register: resultobj5
      
    - name: Dump the result object
      debug:
        msg: '{{ resultobj1 resultobj2 resultobj3 resultobj4 resultobj5 }}'
      