
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster property testing"
  tasks:
    - name: "Cluster property"
      cluster_property:
        os: "{{ ansible_os_family }}"
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: 'stonith-enabled', value: true }
        - { name: 'concurrent-fencing', value: true }
        - { name: 'stonith-timeout', value: '900' }
        - { name: 'stonith-action', value: 'reboot' }
      register: resultobj
      
    - name: Dump the result object
      debug:
        msg: '{{ resultobj }}'
      