
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster resource testing"
  tasks:
    - name: "Ensure cluster resource is absent"
      cluster_resource:
        state: absent
        name: rsc_st_azure
        resource_class: stonith
        resource_type: fence_azure_arm
        options: |
          pcmk_monitor_retries=3
          pcmk_action_limit=2
          power_timeout=140
          pcmk_reboot_timeout=800
      register: resultobj
    - name: "Ensure cluster resource is absent: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Create cluster resource"
      cluster_resource:
        state: present
        name: rsc_st_azure
        resource_class: stonith
        resource_type: fence_azure_arm
        options: |
          pcmk_monitor_retries=3
          pcmk_action_limit=2
          power_timeout=140
          pcmk_reboot_timeout=800
      register: resultobj
    - name: "Create cluster resource: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Ensure idempotence"
      cluster_resource:
        state: present
        name: rsc_st_azure
        resource_class: stonith
        resource_type: fence_azure_arm
        options: |
          pcmk_monitor_retries=3
          pcmk_action_limit=2
          power_timeout=140
          pcmk_reboot_timeout=800
      register: resultobj
    - name: "Ensure idempotence: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Modify the resource"
      cluster_resource:
        state: present
        name: rsc_st_azure
        resource_class: stonith
        resource_type: fence_azure_arm
        options: |
          pcmk_monitor_retries=4
          pcmk_action_limit=3
          power_timeout=240
          pcmk_reboot_timeout=900
      register: resultobj
    - name: "Modify the resource: Output"
      debug:
        msg: '{{ resultobj }}'

    - name: "Try removing nonexistent resource"
      cluster_resource:
        state: absent
        name: idontexist
        resource_class: stonith
        resource_type: fence_azure_arm
        options: |
          pcmk_monitor_retries=4
          pcmk_action_limit=3
          power_timeout=240
          pcmk_reboot_timeout=900
      register: resultobj
    - name: "Try removing nonexistent resource: Output"
      debug:
        msg: '{{ resultobj }}'
      