
- hosts: localhost
  become: yes
  become_user: root
  name: "Cluster resource testing"
  tasks:
    - name: "Cluster resource"
      cluster_resource:
        os: "RedHat"
        state: present
        name: rsc_azure-events
        resource_class: ocf
        resource_provider: heartbeat
        resource_type: auzre-events
        options: |
          op monitor interval=10s
      register: resultobj
      
    - name: Dump the result object
      debug:
        msg: '{{ resultobj }}'
      